### ISSUE TITLE
Highly uniform rates for highly variable trait

### ISSUE THREAD

**Issue by soungalo** [pasraia/RRphylo#7]
Hello, and sorry if this is a noob question - trying RRphylo for the first time and I'm a bit confused by the results.
My data encompasses 497 extant species (no fossils). The trait I'm working with is highly variable and shows strong phylogenetic signal:
`> contMap(tree, data, outline=FALSE, fsize=0.001)`
![image](https://github.com/pasraia/RRphylo/assets/5146503/99fc7d50-8a16-41ac-b278-2f6261a9ddd5)
I ran RRphylo:
`> rrphylo = RRphylo(tree, data)`
and then started exploring the results:
`> hist(rrphylo$rates, breaks=50)`
![image](https://github.com/pasraia/RRphylo/assets/5146503/5742b246-67e2-497e-8728-5b3d33ae81b8)
```
> tip_rates = rrphylo$rates[497:993,]
> contMap(tree, tip_rates, outline=FALSE, fsize=0.001)
```
![image](https://github.com/pasraia/RRphylo/assets/5146503/d810860a-5ff7-4ea4-8a05-69046bc9a1aa)
`> plotBranchbyTrait(euk_tree_phyla10, rrphylo$rates, legend=2000, cex=0.001)`
![image](https://github.com/pasraia/RRphylo/assets/5146503/fbbacaf5-fb6c-4e08-8af3-f1ff9b2aded4)

So it seems like the rate of evolution is quite uniform across the whole tree, but this doesn't make sense to me with the given phenotype in the tips. What am I missing?

Interestingly, RRphylo does detects some rate shifts:
```
> SSauto = search.shift(RR=rrphylo,status.type="clade")
> plotSS = plotShift(rrphylo, SS=SSauto)
> plotSS$plotClades()
```
![image](https://github.com/pasraia/RRphylo/assets/5146503/febc92ff-0fcd-42de-9e86-46885aa474e0)

Can you help me figure out what's going on?

Thanks a lot!

[dataset.Rdata.txt](https://github.com/pasraia/RRphylo/files/11523090/dataset.Rdata.txt)

**Comment by pasraia** [comment]
Hi Lior,
thanks for reaching out on us. The point is that you're using contMap to plot variable rates, which is not advisable since value estimation at the nodes do follow the brownian motion model. We have a new function in the pre-release version of RRphylo that does the job effectively, for both phenotypes and rates (see attached)
[RplotPhen.pdf](https://github.com/pasraia/RRphylo/files/11524458/RplotPhen.pdf)
[RplotRates.pdf](https://github.com/pasraia/RRphylo/files/11524459/RplotRates.pdf)
as you will see, they are highly variable. Since the new function is still unavailable, please contact me separately to get the pre-release version and some how to (we won't let you wait to publish your work)
cheers!
Pas

**Comment by soungalo** [comment]
Thanks for the quick reply. I tried it following [this figure](https://www.nature.com/articles/s41467-022-34656-0/figures/2) from a recent paper, but I get that it's not always a good idea. Anyway, I'll contact you to get the pre-release.

**Comment by pasraia** [comment]
you're welcome Lior
